# Learning Bioinformatics {#learning-bioinformatics}

## Books

### Sequence analysis

* BLAST. Ian Korf, ... O'Reilly, 2003

* Biological sequence analysis: Probabilistic models of proteins and nucleic acids. R. Durbin, S. Eddy, ... Cambridge, 1998.

* Molecular evolution and phylogenetics. M. Nei, S. Kumar. Oxford University Press, 2000.

### Omics technologies

## Community resources

Learning Bioinformatics, as with any other complex topic, can be daunting. Sometimes web sites and software come with good and extended documentation. Because the amount of information can be very large, sometimes it is possible to find short tutorials that can help newcomers to get started. It is important to get a good understanding of the methods being used when the goal is to publish your results. The Bioinformatics community can sometimes help in the learning process by providing solutions to the most frequently encountered problems. Here I will highlight some of the most relevant online communities for the Bioinformatician.

### Biostars

[Biostars](http://biostars.org)

### Bioinformatics channel at Stackexchange

Another useful resource for solving questions related to Bioinformatics might be the [Bioinformatics](https://bioinformatics.stackexchange.com) channel at the Stackexchange network.

### Bioconductor support site

The [Bioconductor support site](https://support.bioconductor.org) provides support for questions related to the use of Bioconductor in particular and R for Bioinformatics more in general.


### How to use the support sites

